// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"cloud-disk/core/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/email/code/register",
				Handler: SendCodeForRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register/user",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login/user",
				Handler: LoginHandler(serverCtx),
			},
		},
	)
}
